{% set version = "4.3.3rc1" %}

package:
  name: compliance-checker
  version: {{ version }}

source:
  url: https://github.com/ioos/compliance-checker/archive/{{ version }}.tar.gz
  sha256: 3369996cb164684d3e41f31bdc35d7d30d63d0d8105a8a9da5142c783a768ba2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - compliance-checker = cchecker:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - setuptools >=15.0
    - owslib >=0.8.3
    - lxml >=3.2.1
    - cf-units >=2
    - requests >=2.2.1
    - isodate >=0.5.4
    - jinja2 >=2.7.3
    - pygeoif >=0.6
    - netcdf4 >=1.4
    - regex >=2017.07.28
    - pendulum >=1.2.4
    - validators >=0.14.2

test:
  source_files:
    - compliance_checker
  requires:
    - pip
    - pytest
    - httpretty
  imports:
    - compliance_checker
    - compliance_checker.cf
    - compliance_checker.tests
  commands:
    - compliance-checker --help

about:
  home: https://github.com/ioos/compliance-checker
  license: Apache-2.0
  license_file:  LICENSE
  summary: 'Checks Datasets and SOS endpoints for standards compliance'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
