{% set version = "4.1.1" %}

package:
  name: compliance-checker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/compliance-checker/compliance-checker-{{ version }}.tar.gz
  sha256: c1c2936f8f9066a48f11dc5859ebadb1c8074c993910c7decb407690d701e416
  patches:
    - httpretty.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - compliance-checker = cchecker:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - owslib >=0.8.3
    - lxml >=3.2.1
    - cf_units >=2
    - requests >=2.2.1
    - isodate >=0.5.4
    - jinja2 >=2.7.3
    - pygeoif >=0.6
    - netcdf4 >=1.4
    - regex 2017.07.28
    - pendulum >=1.2.4
    - tabulate 0.8.2

test:
  source_files:
    - compliance_checker
  requires:
    - pytest
  imports:
    - compliance_checker
    - compliance_checker.cf
    - compliance_checker.tests
  commands:
    - compliance-checker --help
    - pytest -k "not (integration or cell_bounds)" -s -rxs -v compliance_checker

about:
  home: https://github.com/ioos/compliance-checker
  license: Apache 2.0
  license_file:  LICENSE
  summary: 'Checks Datasets and SOS endpoints for standards compliance.'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
