{% set version = "3.1.1" %}

package:
  name: compliance-checker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/compliance-checker/compliance-checker-{{ version }}.tar.gz
  sha256: d4aae3d3e58e7e0fead1249579fd0dc063e5c2f7605d8455fecd9d1b4cf1effa

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - compliance-checker = cchecker:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - owslib >=0.8.3
    - lxml >=3.2.1
    - cf_units >=0.1.1
    - requests >=2.2.1
    - isodate >=0.5.4
    - jinja2 >=2.7.3
    - pygeoif >=0.6
    - netcdf4 >=1.3.0
    - regex 2017.07.28
    - pendulum >=1.2.4

test:
  source_files:
    - compliance_checker
  requires:
    - pytest
    - httpretty  # [not py3k]
  imports:
    - compliance_checker
    - compliance_checker.cf
    - compliance_checker.tests
  commands:
    - py.test -k "not (integration or cell_bounds)" -s -rxs -v compliance_checker  # [not win]
    - compliance-checker --help

about:
  home: https://github.com/ioos/compliance-checker
  license: Apache 2.0
  license_file:  LICENSE
  summary: 'Checks Datasets and SOS endpoints for standards compliance.'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
