{% set version = "4.2.1" %}

package:
  name: compliance-checker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/compliance-checker/compliance-checker-{{ version }}.tar.gz
  sha256: 1cd36cd46fed5bd882d8ddee1a7bcf4cb941d223484a8cbe02e45a7dd3f41ce9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - compliance-checker = cchecker:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools >=15.0
    - owslib >=0.8.3
    - lxml >=3.2.1
    - cf-units >=2
    - requests >=2.2.1
    - isodate >=0.5.4
    - jinja2 >=2.7.3
    - pygeoif >=0.6
    - netcdf4 >=1.4
    - regex >=2017.07.28
    - pendulum >=1.2.4
    - functools32  # [py2k]

test:
  source_files:
    - compliance_checker
  requires:
    - pytest
    - httpretty  # [py2k]
  imports:
    - compliance_checker
    - compliance_checker.cf
    - compliance_checker.tests
  commands:
    - compliance-checker --help
    # Skipping integration, cell_bounds, and dataset_GenericFile
    # b/c the files needed to run them are not in the tarball.
    # skipping test_thredds b/c the dataset upstream changed.
    - pytest -k "not (integration or cell_bounds or dataset_GenericFile or test_thredds or test_ioos_sos)" -s -rxs -v compliance_checker

about:
  home: https://github.com/ioos/compliance-checker
  license: Apache 2.0
  license_file:  LICENSE
  summary: 'Checks Datasets and SOS endpoints for standards compliance'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
